/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Daniele  Caschili
 * Created: 17-mag-2016
 */



CREATE TABLE cliente(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(30),
    cognome         VARCHAR(30),
    username        VARCHAR(30),
    password        VARCHAR(30),
    saldo           BIGINT
);


CREATE TABLE venditore(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(30),
    cognome         VARCHAR(30),
    username        VARCHAR(30),
    password        VARCHAR(30),
    saldo           BIGINT,
    società         VARCHAR(30)
);

CREATE TABLE oggetto(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(30),
    descrizione     VARCHAR(500),
    urlImmagine     VARCHAR(500),
    numeroPezzi     INTEGER,
    prezzo          BIGINT,
    venditore_id    INTEGER,
    
    
    FOREIGN KEY (venditore_id) REFERENCES venditore(id) 
);



INSERT INTO cliente(id, nome, cognome, username, password, saldo)
VALUES(default, 'Mario', 'Rossi', 'Mrossi', '0', 5000000000);

INSERT INTO cliente(id, nome, cognome, username, password, saldo)
VALUES(default, 'Anna', 'Bianchi', 'Abianchi', '1', 450000000);




INSERT INTO venditore(id, nome, cognome, username, password, saldo, società)
VALUES(default, 'Marco', 'Blu', 'Mblu', '2', 999000000000, 'GalacticPrice');

INSERT INTO venditore(id, nome, cognome, username, password, saldo, società)
VALUES(default, 'Gianni', 'Verde', 'Gverde', '3', 550000000000, 'NavalSpace');


INSERT INTO oggetto(id, nome, descrizione, urlImmagine, numeroPezzi, prezzo, venditore_id)
VALUES(default, 'Incrociatore Javelin', 'Incrociatore da guerra, grosso e cattivo!\nLe sue 
        dimensioni la rendon lenta e difficile da manovrare, \nma sarà difficile da abbattere!',
        'Immagini/Javelin.jpg', 10, 55000000000, 1);

INSERT INTO oggetto(id, nome, descrizione, urlImmagine, numeroPezzi, prezzo, venditore_id)
VALUES(default, 'Sabre', 'Sabre, velocissima! Riuscirete a seminare qualunque inseguitore!\n
        Non può reggere scontri prolungati!', 'Immagini/Sabre.jpg', 500, 980000000, 2);

INSERT INTO oggetto(id, nome, descrizione, urlImmagine, numeroPezzi, prezzo, venditore_id)
VALUES(default, 'The endeavor', 'Endeavor, GIGANTESCA! Lunga 100km!\nPotrete raggiungere gli angoli più
        remoti dell''universo senza problemi!\nELETTA ASTRONAVE DELL''ANNO SPACEZON!',
        'Immagini/The_Endeavor.jpg', 1, 90000000000, 1);

INSERT INTO oggetto(id, nome, descrizione, urlImmagine, numeroPezzi, prezzo, venditore_id)
VALUES(default, 'Cutlas Red', 'Nave di medie dimensioni. Massima qualità a un prezzo contenuto.', 'Immagini/CutlasRed.jpg', 250, 5500000000, 2);

INSERT INTO oggetto(id, nome, descrizione, urlImmagine, numeroPezzi, prezzo, venditore_id)
VALUES(default, 'M50 Interceptor', 'Nave da battaglia, piccola e veloce. Notevole potenza di fuoco
        nonostante le dimensioni ridotte!', 'Immagini/M50Interceptor.jpg', 1000, 10000000, 1);






